// type: 0 轮播图
// type: 1, swiper 滚动
// type: 2 swiper 两个滚动
// type: 3 榜单
// type: 4 大图形式
export const NEWGAMES = [
	{
		id: "20",
		name: "猜你喜欢",
		compact: "6",
		styleCode: "gallery",
		showmore: "1",
		categoryList: [],
		rankList: [],
		gameList: [
			{
				id: "364737",
				name: "成长大冒险",
				icon: "http://download.mgc-games.com/access/upload/20190425/5cc17c025bd60.png",
				packageurl: "http://download.mgc-games.com/sdkgame/",
				version: "1.0",
				deviceOrientation: "landscape",
				play_num: "0",
				pic: "http://download.mgc-games.com/access/gamecenter/like/czdmx.png",
				publicity: "灵活移动，靠近敌人，手起刀落，吃豆成长，变身继续大冒险。",
				tags: ["休闲", "对战", "IO"],
				classify: "7",
				backgroundcolor: ""
			},
			{
				id: "364733",
				name: "魔君天下",
				icon: "http://download.mgc-games.com/access/upload/20190423/5cbe87b7d3153.png",
				packageurl: "http://download.mgc-games.com/sdkgame/http://mgcstjz.xmjyhy.com/",
				version: "1.0",
				deviceOrientation: "portrait",
				play_num: "263",
				pic: "http://download.mgc-games.com/access/gamecenter/like/mjtx.png",
				publicity: "割发代首割发代首",
				tags: ["养成", "高智商"],
				classify: "11",
				backgroundcolor: ""
			},
			{
				id: "364732",
				name: "权倾天下",
				icon: "http://download.mgc-games.com/access/upload/20190428/5cc5177af1499.png",
				packageurl: "http://download.mgc-games.com/sdkgame/http://qqtxwd.chinagames.net/menggongchang/",
				version: "1.0",
				deviceOrientation: "portrait",
				play_num: "288",
				pic: "http://download.mgc-games.com/access/gamecenter/like/qqtx.png",
				publicity: "一马当先为民请命，万夫不当无所畏惧。别具匠心的穿越题材养成官斗游戏，从九品芝麻官做起，一步一步攀上高位，让玩家体验权高位重、封候拜将的快感，完美再现古代官场。富甲豪绅作恶多端，公堂之上你将如何选择？偶遇佳人喜结连理，哪位倾国红颜是你的最爱？一日入官场，人生几沉浮，你将能活出怎样的仕途生涯？",
				tags: ["对战", "养成"],
				classify: "11",
				backgroundcolor: ""
			},
			{
				id: "364723",
				name: "合成塔防",
				icon: "http://download.mgc-games.com/access/upload/20190412/5cb03f7bc572f.png",
				packageurl: "http://download.mgc-games.com/sdkgame/364723/idleTower_pack.zip",
				version: "1.0.0",
				deviceOrientation: "portrait",
				play_num: "146",
				pic: "http://download.mgc-games.com/access/gamecenter/like/hctf.png",
				publicity: "欢乐塔防，轻松合成，一起打怪兽~",
				tags: ["休闲", "在线玩", "烧脑"],
				classify: "7",
				backgroundcolor: ""
			},
			{
				id: "364720",
				name: "客官饿了吗",
				icon: "http://download.mgc-games.com/access/upload/20190410/5cad967fde972.png",
				packageurl: "http://download.mgc-games.com/sdkgame/364720/Guest_pack.zip",
				version: "1.2.0",
				deviceOrientation: "portrait",
				play_num: "241",
				pic: "http://download.mgc-games.com/access/gamecenter/like/kgelm.png",
				publicity: "这是一款集模拟经营+合成+收集类游戏\r\n通过给来自各地的客人提供上百种中国传统美食，收获解锁传奇菜谱中的每一道菜品，用心经营升级扩大酒楼规模。最终达成御赐满汉全席，名满全国的皇家传奇酒楼。",
				tags: ["休闲", "点击", "养成"],
				classify: "7",
				backgroundcolor: ""
			},
			{
				id: "364540",
				name: "星星爱消乐",
				icon: "http://download.mgc-games.com/access/upload/20190319/5c91002cdf99d.jpg",
				packageurl: "http://download.mgc-games.com/sdkgame/364540/starslovefun_pack.zip",
				version: "2.1.0",
				deviceOrientation: "portrait",
				play_num: "294",
				pic: "http://download.mgc-games.com/access/gamecenter/like/xxaxl.png",
				publicity: "星星爱消乐",
				tags: ["休闲", "消除", "益智"],
				classify: "7",
				backgroundcolor: ""
			},
			{
				id: "364352",
				name: "街机斗地主",
				icon: "http://download.mgc-games.com/access/upload/20190319/5c909dc73468a.png",
				packageurl: "http://download.mgc-games.com/sdkgame/364352/jiejidoudizhu_pack.zip",
				version: "1.5.0",
				deviceOrientation: "landscape",
				play_num: "229",
				pic: "http://download.mgc-games.com/access/gamecenter/like/jjddz.png",
				publicity: "姚记扑克官方授权！正版斗地主游戏！超多实物奖励的经典玩法（手环、平板等你来）！\r\n真人红包、登录红包、实物奖励、首充豪礼！倾心力作，再造经典！",
				tags: ["斗地主", "棋牌"],
				classify: "7",
				backgroundcolor: ""
			},
			{
				id: "364310",
				name: "吃鸡碰碰车",
				icon: "http://download.mgc-games.com/access/upload/20190319/5c909cb3d5af7.png",
				packageurl: "http://download.mgc-games.com/sdkgame/364310/eatchickenandbumpintoacar_pack.zip",
				version: "2.3.1",
				deviceOrientation: "portrait",
				play_num: "245",
				pic: "http://download.mgc-games.com/access/gamecenter/like/cjppc.png",
				publicity: "多人对战，画风可爱，玩法新颖，等你来战！",
				tags: ["对战", "IO", "在线玩"],
				classify: "7",
				backgroundcolor: ""
			},
			{
				id: "364302",
				name: "星星消除计划",
				icon: "http://download.mgc-games.com/access/upload/20190319/5c909d0f05bfc.png",
				packageurl: "http://download.mgc-games.com/sdkgame/364302/starelimination_pack.zip",
				version: "3.6.0",
				deviceOrientation: "portrait",
				play_num: "173",
				pic: "http://download.mgc-games.com/access/gamecenter/like/xxxcjh.png",
				publicity: "等你来挑战消除世界之中的王者地位！",
				tags: ["休闲", "消除", "单机"],
				classify: "7",
				backgroundcolor: ""
			},
			{
				id: "364019",
				name: "开心跳跳",
				icon: "http://download.mgc-games.com/access/upload/20190227/5c7659c4729d5.png",
				packageurl: "http://download.mgc-games.com/sdkgame/364019/kxtt_pack.zip",
				version: "2.2.0",
				deviceOrientation: "portrait",
				play_num: "119",
				pic: "http://download.mgc-games.com/access/gamecenter/like/kxtt.png",
				publicity: "控制小球不断的向上跳跃，收集更多星星，挑战自己！",
				tags: ["休闲", "弹球", "虐心"],
				classify: "7",
				backgroundcolor: ""
			}]
	},
	{
		id: "21",
		name: "赚金币",
		compact: "5",
		styleCode: "horizontalList",
		showmore: "1",
		categoryList: [],
		rankList: [],
		gameList: [
			{
				id: "364733",
				name: "魔君天下",
				icon: "http://download.mgc-games.com/access/upload/20190423/5cbe87b7d3153.png",
				packageurl: "http://download.mgc-games.com/sdkgame/http://mgcstjz.xmjyhy.com/",
				version: "1.0",
				deviceOrientation: "portrait",
				play_num: "263",
				pic: "",
				publicity: "割发代首割发代首",
				tags: ["养成", "高智商"],
				classify: "11",
				backgroundcolor: ""
			},
			{
				id: "364732",
				name: "权倾天下",
				icon: "http://download.mgc-games.com/access/upload/20190428/5cc5177af1499.png",
				packageurl: "http://download.mgc-games.com/sdkgame/http://qqtxwd.chinagames.net/menggongchang/",
				version: "1.0",
				deviceOrientation: "portrait",
				play_num: "288",
				pic: "",
				publicity: "一马当先为民请命，万夫不当无所畏惧。别具匠心的穿越题材养成官斗游戏，从九品芝麻官做起，一步一步攀上高位，让玩家体验权高位重、封候拜将的快感，完美再现古代官场。富甲豪绅作恶多端，公堂之上你将如何选择？偶遇佳人喜结连理，哪位倾国红颜是你的最爱？一日入官场，人生几沉浮，你将能活出怎样的仕途生涯？",
				tags: ["对战", "养成"],
				classify: "11",
				backgroundcolor: ""
			},
			{
				id: "364720",
				name: "客官饿了吗",
				icon: "http://download.mgc-games.com/access/upload/20190410/5cad967fde972.png",
				packageurl: "http://download.mgc-games.com/sdkgame/364720/Guest_pack.zip",
				version: "1.2.0",
				deviceOrientation: "portrait",
				play_num: "241",
				pic: "",
				publicity: "这是一款集模拟经营+合成+收集类游戏\r\n通过给来自各地的客人提供上百种中国传统美食，收获解锁传奇菜谱中的每一道菜品，用心经营升级扩大酒楼规模。最终达成御赐满汉全席，名满全国的皇家传奇酒楼。",
				tags: ["休闲", "点击", "养成"],
				classify: "7",
				backgroundcolor: ""
			},
			{
				id: "364547",
				name: "拥挤城镇",
				icon: "http://download.mgc-games.com/access/upload/20190320/5c91ec16db047.jpg",
				packageurl: "http://download.mgc-games.com/sdkgame/364547/crowd town_pack.zip",
				version: "2.1.0",
				deviceOrientation: "portrait",
				play_num: "187",
				pic: "",
				publicity: "超魔性的小游戏，一大波小弟跟在你身后，还有什么好怕的！",
				tags: ["休闲", "益智"],
				classify: "7",
				backgroundcolor: ""
			},
			{
				id: "364540",
				name: "星星爱消乐",
				icon: "http://download.mgc-games.com/access/upload/20190319/5c91002cdf99d.jpg",
				packageurl: "http://download.mgc-games.com/sdkgame/364540/starslovefun_pack.zip",
				version: "2.1.0",
				deviceOrientation: "portrait",
				play_num: "294",
				pic: "",
				publicity: "星星爱消乐",
				tags: ["休闲", "消除", "益智"],
				classify: "7",
				backgroundcolor: ""
			},
			{
				id: "364366",
				name: "消消方块传奇",
				icon: "http://download.mgc-games.com/access/upload/20190319/5c909d8713107.png",
				packageurl: "http://download.mgc-games.com/sdkgame/364366/eliminationblock_pack.zip",
				version: "2.2.0",
				deviceOrientation: "portrait",
				play_num: "230",
				pic: "",
				publicity: "纵横变换消除，创意益智休闲！",
				tags: ["休闲", "消除", "单机"],
				classify: "7",
				backgroundcolor: ""
			},
			{
				id: "364333",
				name: "大明皇朝",
				icon: "http://download.mgc-games.com/access/upload/20190227/5c764f580d180.jpg",
				packageurl: "http://download.mgc-games.com/sdkgame/364333/daminghuangchao_pack.zip",
				version: "2.1.0",
				deviceOrientation: "portrait",
				play_num: "167",
				pic: "",
				publicity: "大明皇朝是一款合成养成类的宫斗游戏。1.2亿人都在玩的穿越小游戏，穿越到大明，亲自处理朝政！",
				tags: ["休闲", "益智", "高智商"],
				classify: "7",
				backgroundcolor: ""
			},
			{
				id: "364302",
				name: "星星消除计划",
				icon: "http://download.mgc-games.com/access/upload/20190319/5c909d0f05bfc.png",
				packageurl: "http://download.mgc-games.com/sdkgame/364302/starelimination_pack.zip",
				version: "3.6.0",
				deviceOrientation: "portrait",
				play_num: "173",
				pic: "",
				publicity: "等你来挑战消除世界之中的王者地位！",
				tags: ["休闲", "消除", "单机"],
				classify: "7",
				backgroundcolor: ""
			},
			{
				id: "364289",
				name: "数字传奇",
				icon: "http://download.mgc-games.com/access/upload/20190304/5c7d2dafc6aaf.png",
				packageurl: "http://download.mgc-games.com/sdkgame/364289/digitallegend_pack.zip",
				version: "1.0",
				deviceOrientation: "portrait",
				play_num: "295",
				pic: "",
				publicity: "手指滑动，挑战无线数字，乐趣升级！",
				tags: [],
				classify: "7",
				backgroundcolor: ""
			},
			{
				id: "364019",
				name: "开心跳跳",
				icon: "http://download.mgc-games.com/access/upload/20190227/5c7659c4729d5.png",
				packageurl: "http://download.mgc-games.com/sdkgame/364019/kxtt_pack.zip",
				version: "2.2.0",
				deviceOrientation: "portrait",
				play_num: "119",
				pic: "",
				publicity: "控制小球不断的向上跳跃，收集更多星星，挑战自己！",
				tags: ["休闲", "弹球", "虐心"],
				classify: "7",
				backgroundcolor: ""
			}]
	},
	{
		id: "22",
		name: "年度榜单",
		compact: "9",
		styleCode: "singleRanking",
		showmore: "1",
		categoryList: [],
		rankList: [
			{
				id: "16",
				name: "年度榜单",
				icon: "",
				gameList: [
					{
						id: "364732",
						name: "权倾天下",
						icon: "http://download.mgc-games.com/access/upload/20190428/5cc5177af1499.png",
						packageurl: "http://download.mgc-games.com/sdkgame/http://qqtxwd.chinagames.net/menggongchang/",
						version: "1.0",
						deviceOrientation: "portrait",
						play_num: "288",
						pic: "",
						publicity: "一马当先为民请命，万夫不当无所畏惧。别具匠心的穿越题材养成官斗游戏，从九品芝麻官做起，一步一步攀上高位，让玩家体验权高位重、封候拜将的快感，完美再现古代官场。富甲豪绅作恶多端，公堂之上你将如何选择？偶遇佳人喜结连理，哪位倾国红颜是你的最爱？一日入官场，人生几沉浮，你将能活出怎样的仕途生涯？",
						tags: ["对战", "养成"],
						classify: "11",
						backgroundcolor: ""
					},
					{
						id: "364352",
						name: "街机斗地主",
						icon: "http://download.mgc-games.com/access/upload/20190319/5c909dc73468a.png",
						packageurl: "http://download.mgc-games.com/sdkgame/364352/jiejidoudizhu_pack.zip",
						version: "1.5.0",
						deviceOrientation: "landscape",
						play_num: "229",
						pic: "",
						publicity: "姚记扑克官方授权！正版斗地主游戏！超多实物奖励的经典玩法（手环、平板等你来）！\r\n真人红包、登录红包、实物奖励、首充豪礼！倾心力作，再造经典！",
						tags: ["斗地主", "棋牌"],
						classify: "7",
						backgroundcolor: ""
					},
					{
						id: "364285",
						name: "消灭宝石",
						icon: "http://download.mgc-games.com/access/upload/20190304/5c7d314260cc4.png",
						packageurl: "http://download.mgc-games.com/sdkgame/364285/eradicationofpreciousstones_pack.zip",
						version: "1.0.1",
						deviceOrientation: "portrait",
						play_num: "198",
						pic: "",
						publicity: "集合多种玩法于一体，好玩停不下来！",
						tags: ["休闲", "消除", "单机"],
						classify: "7",
						backgroundcolor: ""
					}]
			}],
		gameList: []
	},
	{
		id: "23",
		name: "指心捕鱼",
		compact: "10",
		styleCode: "bigPic",
		showmore: "2",
		categoryList: [],
		rankList: [],
		gameList: [
			{
				id: "364383",
				name: "指心捕鱼",
				icon: "http://download.mgc-games.com/access/upload/20190319/5c909e4f5d630.png",
				packageurl: "http://download.mgc-games.com/sdkgame/364383/zhixinfish_pack.zip",
				version: "2.1.0",
				deviceOrientation: "landscape",
				play_num: "292",
				pic: "http://download.mgc-games.com/access/gamecenter/pic/zxby.png",
				publicity: "一款从没见过子弹如此宝贵的红包捕鱼产品！",
				tags: ["捕鱼", "斗地主", "棋牌"],
				classify: "7",
				backgroundcolor: ""
			}]
	},
	{
		id: "24",
		name: "新游上线",
		compact: "2",
		styleCode: "moreHorizontalList",
		showmore: "2",
		categoryList: [],
		rankList: [],
		gameList: [
			{
				id: "364676",
				name: "欢乐小农场之疯狂田田",
				icon: "http://download.mgc-games.com/access/upload/20190409/5cac2af1bc850.png",
				packageurl: "http://download.mgc-games.com/sdkgame/364676/huanlexiaonongchang_pack.zip",
				version: "1.1.1",
				deviceOrientation: "portrait",
				play_num: "126",
				pic: "",
				publicity: "《欢乐小农场之疯狂田田》（简称《欢乐小农场》）是一款可爱的农场类经营游戏。在游戏中，你将在手机屏幕内管理一个微型农场，不停的收获农作物，并且用收获来的资金解锁新的地块。你的农场将逐渐充满各种各样的农作物和动物!游戏采用竖版单手操作的模式，可以方便用户随时打开手机进行游戏。同时引入了大量的经营和社交类游戏要素，使游戏在充满了趣味性的同时，也有与其他玩家进行交互的乐趣。\r\n\r\n玩法介绍\r\n\r\n1，收获",
				tags: ["休闲", "单机", "养成"],
				classify: "7",
				backgroundcolor: ""
			},
			{
				id: "364383",
				name: "指心捕鱼",
				icon: "http://download.mgc-games.com/access/upload/20190319/5c909e4f5d630.png",
				packageurl: "http://download.mgc-games.com/sdkgame/364383/zhixinfish_pack.zip",
				version: "2.1.0",
				deviceOrientation: "landscape",
				play_num: "292",
				pic: "",
				publicity: "一款从没见过子弹如此宝贵的红包捕鱼产品！",
				tags: ["捕鱼", "斗地主", "棋牌"],
				classify: "7",
				backgroundcolor: ""
			},
			{
				id: "364310",
				name: "吃鸡碰碰车",
				icon: "http://download.mgc-games.com/access/upload/20190319/5c909cb3d5af7.png",
				packageurl: "http://download.mgc-games.com/sdkgame/364310/eatchickenandbumpintoacar_pack.zip",
				version: "2.3.1",
				deviceOrientation: "portrait",
				play_num: "245",
				pic: "",
				publicity: "多人对战，画风可爱，玩法新颖，等你来战！",
				tags: ["对战", "IO", "在线玩"],
				classify: "7",
				backgroundcolor: ""
			},
			{
				id: "364308",
				name: "黑洞也疯狂",
				icon: "http://download.mgc-games.com/access/upload/20190308/5c821b860bb23.png",
				packageurl: "http://download.mgc-games.com/sdkgame/364308/blackholefighting_pack.zip",
				version: "1.0.1",
				deviceOrientation: "portrait",
				play_num: "203",
				pic: "",
				publicity: "操控黑洞吞噬所有，包括你的对手！",
				tags: ["对战", "IO", "在线玩"],
				classify: "7",
				backgroundcolor: ""
			},
			{
				id: "364306",
				name: "欢乐打豆豆",
				icon: "http://download.mgc-games.com/access/upload/20190319/5c909ce383dce.png",
				packageurl: "http://download.mgc-games.com/sdkgame/364306/happyhbeanbeans_pack.zip",
				version: "1.0.0",
				deviceOrientation: "portrait",
				play_num: "217",
				pic: "",
				publicity: "不让吃饭？OK！不让睡觉，也OK，不让打豆豆，那是不可能的！",
				tags: [],
				classify: "7",
				backgroundcolor: ""
			},
			{
				id: "364287",
				name: "六边形拼图",
				icon: "http://download.mgc-games.com/access/upload/20190304/5c7d2ed78f002.png",
				packageurl: "http://download.mgc-games.com/sdkgame/364287/hexagonpuzzle_pack.zip",
				version: "2.1.0",
				deviceOrientation: "portrait",
				play_num: "135",
				pic: "",
				publicity: "方块于平涂的绝妙搭配，神秘的智力大考验。",
				tags: ["休闲", "消除", "六边形"],
				classify: "7",
				backgroundcolor: ""
			},
			{
				id: "364046",
				name: "开心消一消2",
				icon: "http://download.mgc-games.com/access/upload/20181223/5c1f9a1352a58.png",
				packageurl: "http://download.mgc-games.com/sdkgame/364046/happydispel 2_pack.zip",
				version: "1.1.0",
				deviceOrientation: "portrait",
				play_num: "129",
				pic: "",
				publicity: "触动之间，体验消除的快感！",
				tags: [],
				classify: "7",
				backgroundcolor: ""
			},
			{
				id: "363961",
				name: "开心BT弹球",
				icon: "http://download.mgc-games.com/access/upload/20190301/5c78e9105f3d6.png",
				packageurl: "http://download.mgc-games.com/sdkgame/363961/tq_pack.zip",
				version: "2.0.0",
				deviceOrientation: "portrait",
				play_num: "149",
				pic: "",
				publicity: "方与圆的碰撞，每一步都需要精心算计！",
				tags: ["休闲", "弹球", "超爽"],
				classify: "7",
				backgroundcolor: ""
			},
			{
				id: "363958",
				name: "开心祖玛",
				icon: "http://download.mgc-games.com/access/upload/20181206/5c08f9484a110.png",
				packageurl: "http://download.mgc-games.com/sdkgame/363958/zmlz_pack.zip",
				version: "2.1.0",
				deviceOrientation: "portrait",
				play_num: "129",
				pic: "",
				publicity: "让人着迷的金典祖玛玩法，无尽闯关乐趣无穷！",
				tags: ["休闲", "单机", "益智"],
				classify: "7",
				backgroundcolor: ""
			}]
	},
	{
		id: "25",
		name: "超级大明星",
		compact: "10",
		styleCode: "bigPic",
		showmore: "2",
		categoryList: [],
		rankList: [],
		gameList: [
			{
				id: "364730",
				name: "超级大明星",
				icon: "http://download.mgc-games.com/access/upload/20190417/5cb6cb048256c.png",
				packageurl: "http://download.mgc-games.com/sdkgame/",
				version: "1.0",
				deviceOrientation: "portrait",
				play_num: "232",
				pic: "http://download.mgc-games.com/access/gamecenter/pic/cjdmx.png",
				publicity: "《超级大明星》是一款明星养成为主线的女性休闲小游戏，玩家在这里创建可以经纪公司、招募艺人、装扮艺人、训练艺人等，将她们培养打造成练习生、网红、明星，甚至是国际巨星，完成你的造星梦。",
				tags: ["休闲", "养成", "女频"],
				classify: "7",
				backgroundcolor: ""
			}]
	},
	{
		id: "26",
		name: "休闲益智",
		compact: "5",
		styleCode: "horizontalList",
		showmore: "1",
		categoryList: [],
		rankList: [],
		gameList: [
			{
				id: "364543",
				name: "疯狂加一",
				icon: "http://download.mgc-games.com/access/upload/20190319/5c9101564524f.jpg",
				packageurl: "http://download.mgc-games.com/sdkgame/364543/crazyplusone_pack.zip",
				version: "2.1.0",
				deviceOrientation: "portrait",
				play_num: "134",
				pic: "",
				publicity: "疯狂加一",
				tags: ["休闲", "益智"],
				classify: "7",
				backgroundcolor: ""
			},
			{
				id: "364281",
				name: "多牛百变方块",
				icon: "http://download.mgc-games.com/access/upload/20190304/5c7d30cf5f137.png",
				packageurl: "http://download.mgc-games.com/sdkgame/364281/varietycube_pack.zip",
				version: "2.1.0",
				deviceOrientation: "portrait",
				play_num: "132",
				pic: "",
				publicity: "多项消除，不一样的方块小游戏。",
				tags: ["休闲", "消除", "六边形"],
				classify: "7",
				backgroundcolor: ""
			},
			{
				id: "364280",
				name: "数字方块",
				icon: "http://download.mgc-games.com/access/upload/20190304/5c7d30fd26efe.png",
				packageurl: "http://download.mgc-games.com/sdkgame/364280/numberblock_pack.zip",
				version: "2.0.0",
				deviceOrientation: "portrait",
				play_num: "231",
				pic: "",
				publicity: "数字方块是一款以2048为主题的益智小游戏。",
				tags: ["休闲", "单机", "益智"],
				classify: "7",
				backgroundcolor: ""
			},
			{
				id: "364070",
				name: "开心矿工",
				icon: "http://download.mgc-games.com/access/upload/20181230/5c28c9fc87ac8.jpg",
				packageurl: "http://download.mgc-games.com/sdkgame/364070/Golden Miner_pack.zip",
				version: "2.0.0",
				deviceOrientation: "portrait",
				play_num: "146",
				pic: "",
				publicity: "我家里有矿，挖矿挖出个全国首富\r\n",
				tags: ["对战", "在线玩", "挖矿"],
				classify: "7",
				backgroundcolor: ""
			},
			{
				id: "364018",
				name: "开心球球",
				icon: "http://download.mgc-games.com/access/upload/20190227/5c7658b28328b.png",
				packageurl: "http://download.mgc-games.com/sdkgame/364018/hltq_pack.zip",
				version: "2.1.0",
				deviceOrientation: "portrait",
				play_num: "185",
				pic: "",
				publicity: "生命在于运动，活动一下你的运动细胞吧\r\n",
				tags: [],
				classify: "7",
				backgroundcolor: ""
			},
			{
				id: "363940",
				name: "史上最坑爹的游戏13",
				icon: "http://download.mgc-games.com/access/upload/20190227/5c765c54a76f3.png",
				packageurl: "http://download.mgc-games.com/sdkgame/363940/sxk13_pack.zip",
				version: "2.1.0",
				deviceOrientation: "portrait",
				play_num: "249",
				pic: "",
				publicity: "未来科技篇，史小坑将在游戏里带领大家进入科技新纪元",
				tags: [],
				classify: "7",
				backgroundcolor: ""
			},
			{
				id: "363934",
				name: "史上最坑爹的游戏8",
				icon: "http://download.mgc-games.com/access/upload/20190227/5c765c7a537c7.png",
				packageurl: "http://download.mgc-games.com/sdkgame/363934/shishangzuikengdieyouxi8_pack.zip",
				version: "2.1.0",
				deviceOrientation: "portrait",
				play_num: "136",
				pic: "",
				publicity: "清奇恶搞乐趣无穷，不坑爹算我输\r\n",
				tags: ["解谜", "史小坑", "坑爹游戏"],
				classify: "7",
				backgroundcolor: ""
			},
			{
				id: "363930",
				name: "打打捕鱼",
				icon: "http://download.mgc-games.com/access/upload/20190227/5c765c184230b.png",
				packageurl: "http://download.mgc-games.com/sdkgame/363930/lhfish_pack.zip",
				version: "2.0.0",
				deviceOrientation: "landscape",
				play_num: "276",
				pic: "",
				publicity: "打打捕鱼——网网有惊喜，点点全归你！",
				tags: ["捕鱼", "在线玩"],
				classify: "7",
				backgroundcolor: ""
			}]
	},
	{
		id: "27",
		name: "街机斗地主",
		compact: "10",
		styleCode: "bigPic",
		showmore: "2",
		categoryList: [],
		rankList: [],
		gameList: [
			{
				id: "364352",
				name: "街机斗地主",
				icon: "http://download.mgc-games.com/access/upload/20190319/5c909dc73468a.png",
				packageurl: "http://download.mgc-games.com/sdkgame/364352/jiejidoudizhu_pack.zip",
				version: "1.5.0",
				deviceOrientation: "landscape",
				play_num: "229",
				pic: "http://download.mgc-games.com/access/gamecenter/pic/jjddz.png",
				publicity: "姚记扑克官方授权！正版斗地主游戏！超多实物奖励的经典玩法（手环、平板等你来）！\r\n真人红包、登录红包、实物奖励、首充豪礼！倾心力作，再造经典！",
				tags: ["斗地主", "棋牌"],
				classify: "7",
				backgroundcolor: ""
			}]
	},
	{
		id: "28",
		name: "今日推荐",
		compact: "2",
		styleCode: "moreHorizontalList",
		showmore: "2",
		categoryList: [],
		rankList: [],
		gameList: [
			{
				id: "364723",
				name: "合成塔防",
				icon: "http://download.mgc-games.com/access/upload/20190412/5cb03f7bc572f.png",
				packageurl: "http://download.mgc-games.com/sdkgame/364723/idleTower_pack.zip",
				version: "1.0.0",
				deviceOrientation: "portrait",
				play_num: "146",
				pic: "",
				publicity: "欢乐塔防，轻松合成，一起打怪兽~",
				tags: ["休闲", "在线玩", "烧脑"],
				classify: "7",
				backgroundcolor: ""
			},
			{
				id: "364342",
				name: "凡人飞仙传",
				icon: "http://download.mgc-games.com/access/upload/20190429/5cc6ab4d55ee3.png",
				packageurl: "http://download.mgc-games.com/sdkgame/http://rhh5.520cai.com/game_link/49/6.html",
				version: "1.0",
				deviceOrientation: "portrait",
				play_num: "152",
				pic: "",
				publicity: "《凡人飞仙传》是首款跨服空战仙侠H5游戏，创新无限制浮空玩法、御剑飞行，纵横三界，感受修仙者的逍遥自在。数百种仙法魔功、千人同屏，华丽特效呈现最爽快的仙界大战。更有华丽时装、法宝灵兽等百变玩法，带你畅游最精彩的仙侠世界。\n\n唯美仙侠 如临仙境\n从仙气飘飘的灵山到威严肃杀的仙宫、再到热闹无比的人间，数百张高清唯美大地图，为你呈现一个精彩的仙侠世界。\n\n御剑飞行 浮空激战\n创新浮空玩法，千",
				tags: ["虐心", "高智商", "超爽"],
				classify: "11",
				backgroundcolor: ""
			},
			{
				id: "364335",
				name: "幻想西游",
				icon: "http://download.mgc-games.com/access/upload/20190218/5c6a8a3777fca.png",
				packageurl: "http://download.mgc-games.com/sdkgame/http://www.xcvgame.cn/mgc/hxxy/login.php",
				version: "1.0",
				deviceOrientation: "portrait",
				play_num: "292",
				pic: "",
				publicity: "《幻想西游》是一款回合制RPG游戏。\n故事背景是以西游记取经的路程为主线，玩家可以选择不同种族的身份，重新经历这场西天取经的心路历程。",
				tags: [],
				classify: "11",
				backgroundcolor: ""
			},
			{
				id: "364284",
				name: "飞行棋",
				icon: "http://download.mgc-games.com/access/upload/20190304/5c7d30e502d80.png",
				packageurl: "http://download.mgc-games.com/sdkgame/364284/flightchess_pack.zip",
				version: "2.0.0",
				deviceOrientation: "portrait",
				play_num: "281",
				pic: "",
				publicity: "王牌飞行员申请出战！",
				tags: [],
				classify: "7",
				backgroundcolor: ""
			},
			{
				id: "364090",
				name: "泡泡龙",
				icon: "http://download.mgc-games.com/access/upload/20190227/5c76530ded24a.jpg",
				packageurl: "http://download.mgc-games.com/sdkgame/364090/Puzzle Bobble_pack.zip",
				version: "2.0.0",
				deviceOrientation: "portrait",
				play_num: "202",
				pic: "",
				publicity: "儿时的回忆，根本停不下来的泡泡龙！\r\n",
				tags: [],
				classify: "7",
				backgroundcolor: ""
			},
			{
				id: "364054",
				name: "书香小说",
				icon: "http://download.mgc-games.com/access/upload/20190118/5c41301e55148.png",
				packageurl: "http://download.mgc-games.com/sdkgame/http://simple-reader.sxyj.net/menggongchang",
				version: "1.0",
				deviceOrientation: "portrait",
				play_num: "121",
				pic: "",
				publicity: "书香小说",
				tags: ["小说", "男频", "女频"],
				classify: "10",
				backgroundcolor: ""
			},
			{
				id: "363973",
				name: "守护英雄",
				icon: "http://download.mgc-games.com/access/upload/20181207/5c0a54f2e7cb0.png",
				packageurl: "http://download.mgc-games.com/sdkgame/363973/shyx_pack.zip",
				version: "1.0.1",
				deviceOrientation: "portrait",
				play_num: "225",
				pic: "",
				publicity: "简单，却不单调，用指尖守护小鸟！",
				tags: ["休闲", "超难", "虐心"],
				classify: "7",
				backgroundcolor: ""
			},
			{
				id: "363972",
				name: "开心贪吃蛇",
				icon: "http://download.mgc-games.com/access/upload/20190227/5c765aa8b95fa.png",
				packageurl: "http://download.mgc-games.com/sdkgame/363972/zqtcs_pack.zip",
				version: "1.0.6",
				deviceOrientation: "portrait",
				play_num: "182",
				pic: "",
				publicity: "超火爆的的贪吃蛇小游戏，大家都爱玩的休闲游戏\r\n",
				tags: [],
				classify: "7",
				backgroundcolor: ""
			},
			{
				id: "363965",
				name: "挑战一笔画",
				icon: "http://download.mgc-games.com/access/upload/20181225/5c21d4b993523.png",
				packageurl: "http://download.mgc-games.com/sdkgame/363965/tzybh_pack.zip",
				version: "1.2.0",
				deviceOrientation: "portrait",
				play_num: "294",
				pic: "",
				publicity: "每天动动脑，挑战一笔画！",
				tags: [],
				classify: "7",
				backgroundcolor: ""
			},
			{
				id: "363949",
				name: "风流霸业",
				icon: "http://download.mgc-games.com/access/upload/20181129/5bff51bb04bae.png",
				packageurl: "http://download.mgc-games.com/sdkgame/363949/flby_pack.zip",
				version: "1.1.1",
				deviceOrientation: "portrait",
				play_num: "269",
				pic: "",
				publicity: "开启策略新玩法，江山美人双丰收。",
				tags: ["在线玩", "传奇", "PK"],
				classify: "7",
				backgroundcolor: ""
			},
			{
				id: "363943",
				name: "史上最坑爹的游戏14",
				icon: "http://download.mgc-games.com/access/upload/20181127/5bfd0e2737fb6.png",
				packageurl: "http://download.mgc-games.com/sdkgame/363943/sxk14_pack.zip",
				version: "2.1.0",
				deviceOrientation: "portrait",
				play_num: "291",
				pic: "",
				publicity: "史诗级神话背景，毁天灭地的战斗画面，眼花缭乱的法术特效",
				tags: [],
				classify: "7",
				backgroundcolor: ""
			}]
	},
	{
		id: "29",
		name: "西游后传",
		compact: "10",
		styleCode: "bigPic",
		showmore: "2",
		categoryList: [],
		rankList: [],
		gameList: [
			{
				id: "363490",
				name: "西游后传",
				icon: "http://download.mgc-games.com/access/upload/20180915/5b9c886acd0fe.png",
				packageurl: "http://download.mgc-games.com/sdkgame/363490/xiyouhouchuan_pack.zip",
				version: "3.5.0",
				deviceOrientation: "portrait",
				play_num: "128",
				pic: "http://download.mgc-games.com/access/gamecenter/pic/xyhz.png",
				publicity: "十五年经典，梦回西游，封妖挖宝。",
				tags: ["在线玩"],
				classify: "7",
				backgroundcolor: ""
			}]
	},
	{
		id: "30",
		name: "轻松玩",
		compact: "5",
		styleCode: "horizontalList",
		showmore: "1",
		categoryList: [],
		rankList: [],
		gameList: [
			{
				id: "364340",
				name: "绝世好剑",
				icon: "http://download.mgc-games.com/access/upload/20190227/5c764f1c1e4d7.jpg",
				packageurl: "http://download.mgc-games.com/sdkgame/364340/JSHJ_pack.zip",
				version: "2.0.0",
				deviceOrientation: "portrait",
				play_num: "105",
				pic: "",
				publicity: "超好玩的合成游戏，还不快来试试！",
				tags: ["休闲", "点击", "养成"],
				classify: "7",
				backgroundcolor: ""
			},
			{
				id: "364313",
				name: "仙剑缘",
				icon: "http://download.mgc-games.com/access/upload/20190301/5c78a435234c6.png",
				packageurl: "http://download.mgc-games.com/sdkgame/http://www.jyhdhh.com/suyi2/client/index.html?game_key=51555f243ebd3f36df93f2a230204346",
				version: "1.0",
				deviceOrientation: "portrait",
				play_num: "230",
				pic: "",
				publicity: "《剑山奇缘》 是一款经典武侠题材的手机游戏 ，结合了外置和mmorpg的元素，玩家可以在探索世界，并且获得装备和材料养成角色，从而成为世界霸主。",
				tags: [],
				classify: "11",
				backgroundcolor: ""
			},
			{
				id: "364021",
				name: "开心守护飞飞",
				icon: "http://download.mgc-games.com/access/upload/20190227/5c7659b287639.png",
				packageurl: "http://download.mgc-games.com/sdkgame/364021/shff_pack.zip",
				version: "2.1.0",
				deviceOrientation: "portrait",
				play_num: "236",
				pic: "",
				publicity: "操纵小圈圈化身守护神，棒飞飞度过难关吧！",
				tags: [],
				classify: "7",
				backgroundcolor: ""
			},
			{
				id: "363968",
				name: "超级火炮",
				icon: "http://download.mgc-games.com/access/upload/20181207/5c09f5ddb3b88.png",
				packageurl: "http://download.mgc-games.com/sdkgame/363968/cjhp_pack.zip",
				version: "1.0.1",
				deviceOrientation: "portrait",
				play_num: "186",
				pic: "",
				publicity: "玩法升级、火炮升级，华丽特效！",
				tags: ["休闲", "超难", "虐心"],
				classify: "7",
				backgroundcolor: ""
			},
			{
				id: "363967",
				name: "开心六角消消乐",
				icon: "http://download.mgc-games.com/access/upload/20181204/5c066822680c5.jpg",
				packageurl: "http://download.mgc-games.com/sdkgame/363967/ljxxx_pack.zip",
				version: "2.1.0",
				deviceOrientation: "portrait",
				play_num: "153",
				pic: "",
				publicity: "巧妙的拼接，智慧的碰撞，充满挑战的智力大考验！",
				tags: ["休闲", "消除", "六边形"],
				classify: "7",
				backgroundcolor: ""
			},
			{
				id: "363966",
				name: "超级连线",
				icon: "http://download.mgc-games.com/access/upload/20190314/5c8a2edfe8881.png",
				packageurl: "http://download.mgc-games.com/sdkgame/363966/cjlianxian.zip",
				version: "1.0.0",
				deviceOrientation: "portrait",
				play_num: "227",
				pic: "",
				publicity: "一连就上瘾，朋友圈的好友都在玩\r\n",
				tags: [],
				classify: "7",
				backgroundcolor: ""
			},
			{
				id: "363962",
				name: "黄金打方块",
				icon: "http://download.mgc-games.com/access/upload/20181207/5c0a3a6141684.png",
				packageurl: "http://download.mgc-games.com/sdkgame/363962/hjdfk_pack.zip",
				version: "1.0.0",
				deviceOrientation: "portrait",
				play_num: "248",
				pic: "",
				publicity: "经典打方块游戏，让人沉迷其中，难以自拔！",
				tags: ["休闲", "单机", "超难"],
				classify: "7",
				backgroundcolor: ""
			},
			{
				id: "363937",
				name: "史上最坑爹的游戏12",
				icon: "http://download.mgc-games.com/access/upload/20190227/5c765c6518ac6.png",
				packageurl: "http://download.mgc-games.com/sdkgame/363937/sxk12_pack.zip",
				version: "2.1.0",
				deviceOrientation: "portrait",
				play_num: "151",
				pic: "",
				publicity: "追女日记悄悄来袭，意想不到的套路",
				tags: [],
				classify: "7",
				backgroundcolor: ""
			},
			{
				id: "363490",
				name: "西游后传",
				icon: "http://download.mgc-games.com/access/upload/20180915/5b9c886acd0fe.png",
				packageurl: "http://download.mgc-games.com/sdkgame/363490/xiyouhouchuan_pack.zip",
				version: "3.5.0",
				deviceOrientation: "portrait",
				play_num: "128",
				pic: "",
				publicity: "十五年经典，梦回西游，封妖挖宝。",
				tags: ["在线玩"],
				classify: "7",
				backgroundcolor: ""
			}]
	},
	{
		id: "31",
		name: "六边形消除",
		compact: "10",
		styleCode: "bigPic",
		showmore: "2",
		categoryList: [],
		rankList: [],
		gameList: [
			{
				id: "364286",
				name: "六边形消除",
				icon: "http://download.mgc-games.com/access/upload/20190304/5c7d2f4c173e9.png",
				packageurl: "http://download.mgc-games.com/sdkgame/364286/hexagonelimination_pack.zip",
				version: "1.0",
				deviceOrientation: "portrait",
				play_num: "245",
				pic: "http://download.mgc-games.com/access/gamecenter/pic/lbxxc.jpg",
				publicity: "全新玩法，纵横变换，烧脑有趣，创意满满！",
				tags: ["休闲", "消除", "六边形"],
				classify: "7",
				backgroundcolor: ""
			}
		]
	}
]

export const BANNER = {
	id: "19",
	name: "轮播图",
	compact: "1",
	styleCode: "rotationChart",
	showmore: "2",
	categoryList: [],
	rankList: [],
	gameList: [
		{
			id: "364732",
			name: "权倾天下",
			icon: "http://download.mgc-games.com/access/upload/20190428/5cc5177af1499.png",
			packageurl: "http://download.mgc-games.com/sdkgame/http://qqtxwd.chinagames.net/menggongchang/",
			version: "1.0",
			deviceOrientation: "portrait",
			play_num: "288",
			pic: "http://download.mgc-games.com/access/gamecenter/banner/qqtx.png",
			publicity: "一马当先为民请命，万夫不当无所畏惧。别具匠心的穿越题材养成官斗游戏，从九品芝麻官做起，一步一步攀上高位，让玩家体验权高位重、封候拜将的快感，完美再现古代官场。富甲豪绅作恶多端，公堂之上你将如何选择？偶遇佳人喜结连理，哪位倾国红颜是你的最爱？一日入官场，人生几沉浮，你将能活出怎样的仕途生涯？",
			tags: ["对战", "养成"],
			classify: "11",
			backgroundcolor: ""
		},
		{
			id: "364720",
			name: "客官饿了吗",
			icon: "http://download.mgc-games.com/access/upload/20190410/5cad967fde972.png",
			packageurl: "http://download.mgc-games.com/sdkgame/364720/Guest_pack.zip",
			version: "1.2.0",
			deviceOrientation: "portrait",
			play_num: "241",
			pic: "http://download.mgc-games.com/access/gamecenter/banner/kgelm.jpeg",
			publicity: "这是一款集模拟经营+合成+收集类游戏\r\n通过给来自各地的客人提供上百种中国传统美食，收获解锁传奇菜谱中的每一道菜品，用心经营升级扩大酒楼规模。最终达成御赐满汉全席，名满全国的皇家传奇酒楼。",
			tags: ["休闲", "点击", "养成"],
			classify: "7",
			backgroundcolor: ""
		},
		{
			id: "364333",
			name: "大明皇朝",
			icon: "http://download.mgc-games.com/access/upload/20190227/5c764f580d180.jpg",
			packageurl: "http://download.mgc-games.com/sdkgame/364333/daminghuangchao_pack.zip",
			version: "2.1.0",
			deviceOrientation: "portrait",
			play_num: "167",
			pic: "http://download.mgc-games.com/access/gamecenter/banner/dmhc.png",
			publicity: "大明皇朝是一款合成养成类的宫斗游戏。1.2亿人都在玩的穿越小游戏，穿越到大明，亲自处理朝政！",
			tags: ["休闲", "益智", "高智商"],
			classify: "7",
			backgroundcolor: ""
		}
	]
}
