// type: 0 轮播图
// type: 1, swiper 滚动
// type: 2 swiper 两个滚动
// type: 3 榜单
// type: 4 大图形式
export const NEWGAMES = [
	{
		id: "20",
		name: "猜你喜欢",
		compact: "6",
		styleCode: "gallery",
		showmore: "1",
		categoryList: [],
		rankList: [],
		gameList: [
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20190711/5d26e433efd36.png",
				"id": 364856,
				"marker": "",
				"name": "逃出公司",
				"packageurl": "http://download.mgc-games.com/sdkgame/364856/ditchingwork_pack.zip",
				"pic": "http://download.mgc-games.com/access/upload/20200104/5e10213b85101.png",
				"play_num": 143,
				"publicity": "一入职场深似海，从此下班是路人！每天都是日常加班！！啊，今天我必须要翘班！\n这是一款躲避魔鬼上司的监视，通过斗智斗勇从办公室逃脱的密室・解谜游戏。\n【游戏特色】\n24个关卡，每关都有不同惊喜等着你；\n办公室内陷阱多多，请万分小心，看似平静的背后可能隐藏着巨大阴谋哦\n游戏预埋隐藏关卡等你挑战，或跳槽或加班由你选择；\n谨慎选择道具，它可能让你升上天堂，也可能让你坠入地狱；",
				"tags": ["解谜"],
				"title": "",
				"version": "1.3.8"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20191206/5de9c789596e0.png",
				"id": 1000206,
				"marker": "",
				"name": "乐动球球",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000206/yuedongqiuqiu_pack.zip",
				"pic": "http://download.mgc-games.com/access/upload/20200111/5e197d7ac7f5e.png",
				"play_num": 471,
				"publicity": "《乐动球球》是一款创新的音乐节奏游戏。戴上耳机，打开游戏，一秒钟置身于幻想的世界，跟随音乐节奏嗨起来！",
				"tags": ["休闲", "弹球", "超爽"],
				"title": "",
				"version": "1.0.1"
			},
			{
				id: "364723",
				name: "合成塔防",
				icon: "http://download.mgc-games.com/access/upload/20190412/5cb03f7bc572f.png",
				packageurl: "http://download.mgc-games.com/sdkgame/364723/idleTower_pack.zip",
				version: "1.0.0",
				deviceOrientation: "portrait",
				play_num: "146",
				pic: "http://download.mgc-games.com/access/gamecenter/like/hctf.png",
				publicity: "欢乐塔防，轻松合成，一起打怪兽~",
				tags: ["休闲", "在线玩", "烧脑"],
				classify: "7",
				backgroundcolor: ""
			},
			{
				id: "364310",
				name: "吃鸡碰碰车",
				icon: "http://download.mgc-games.com/access/upload/20190319/5c909cb3d5af7.png",
				packageurl: "http://download.mgc-games.com/sdkgame/364310/eatchickenandbumpintoacar_pack.zip",
				version: "2.3.1",
				deviceOrientation: "portrait",
				play_num: "245",
				pic: "http://download.mgc-games.com/access/gamecenter/like/cjppc.png",
				publicity: "多人对战，画风可爱，玩法新颖，等你来战！",
				tags: ["对战", "IO", "在线玩"],
				classify: "7",
				backgroundcolor: ""
			},
			{
				id: "364302",
				name: "星星消除计划",
				icon: "http://download.mgc-games.com/access/upload/20190319/5c909d0f05bfc.png",
				packageurl: "http://download.mgc-games.com/sdkgame/364302/starelimination_pack.zip",
				version: "3.6.0",
				deviceOrientation: "portrait",
				play_num: "173",
				pic: "http://download.mgc-games.com/access/gamecenter/like/xxxcjh.png",
				publicity: "等你来挑战消除世界之中的王者地位！",
				tags: ["休闲", "消除", "单机"],
				classify: "7",
				backgroundcolor: ""
			}]
	},
	{
		id: "21",
		name: "赚金币",
		compact: "5",
		styleCode: "horizontalList",
		showmore: "1",
		categoryList: [],
		rankList: [],
		gameList: [
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20191206/5de9c66a46adf.png",
				"id": 1000257,
				"marker": "",
				"name": "恐龙都市大乱斗",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000257/Dinosaur Rampage_pack.zip",
				"pic": "",
				"play_num": 576,
				"publicity": "恐龙都市大乱斗一款非常有趣的io对战休闲游戏。这款游戏画面简洁明了，但是玩法非常魔性，玩家在游戏里面扮演远古时代的霸王龙，玩家要做的只是滑动即可控制恐龙。摧毁城市，比对手更多地吞噬人类。",
				"tags": ["对战", "IO"],
				"title": "",
				"version": "1.1.0"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20191206/5de9c5fc5b10b.png",
				"id": 1000259,
				"marker": "",
				"name": "女帝成长计划",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000259/Queen ascended the throne_pack.zip",
				"pic": "",
				"play_num": 120,
				"publicity": "女帝成长计划是一款古风类养成游戏，在这里，虽然你生命坎坷将经受很多的磨难，但完成一系列的磨炼，直至掌握了多样的谋略，才可以成功的在宫廷之中生存下去，最后成为一代女帝！",
				"tags": ["养成", "女频"],
				"title": "",
				"version": "1.1.1"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20190905/5d70a1afc639d.png",
				"id": 365015,
				"marker": "",
				"name": "骑士荣耀",
				"packageurl": "http://download.mgc-games.com/sdkgame/365015/Knight Glory_pack.zip",
				"pic": "",
				"play_num": 357,
				"publicity": "《骑士荣耀》是一款卡牌合成与战斗场景融为一体玩法的创意游戏，人魔大陆战争为背景的经典故事题材。\n游戏玩法介绍：\n战斗关卡\n战斗副本\npk竞技场\n英雄排行榜",
				"tags": ["超爽", "竞技", "策略"],
				"title": "",
				"version": "1.0.2"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20190930/5d91a65d3c724.jpg",
				"id": 364547,
				"marker": "",
				"name": "拥挤城镇",
				"packageurl": "http://download.mgc-games.com/sdkgame/364547/crowd town_pack.zip",
				"pic": "",
				"play_num": 98,
				"publicity": "超魔性的小游戏，一大波小弟跟在你身后，还有什么好怕的！",
				"tags": ["竞技"],
				"title": "",
				"version": "2.2.7"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20190319/5c909d8713107.png",
				"id": 364366,
				"marker": "",
				"name": "消消方块传奇",
				"packageurl": "http://download.mgc-games.com/sdkgame/364366/eliminationblock_pack.zip",
				"pic": "",
				"play_num": 206,
				"publicity": "纵横变换消除，创意益智休闲！",
				"tags": ["益智"],
				"title": "",
				"version": "2.2.4"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "01-06",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20191206/5de9c610ab02a.png",
				"id": 1000258,
				"marker": "",
				"name": "飙速摩托车",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000258/Speedbike_pack.zip",
				"pic": "",
				"play_num": 120,
				"publicity": "追求速度，突破经典！立刻发动你的引擎，在城市中挑战自我，冲击高速，成为传奇摩托车手！",
				"tags": ["跑酷", "竞技"],
				"title": "",
				"version": "1.0.1"
			}
		]
	},
	{
		id: "22",
		name: "年度榜单",
		compact: "9",
		styleCode: "singleRanking",
		showmore: "1",
		categoryList: [],
		rankList: [
			{
				id: "16",
				name: "年度榜单",
				icon: "",
				gameList: [
					{
						"amount": "",
						"backgroundcolor": "",
						"classify": 7,
						"classify_game_id": "0",
						"deviceOrientation": "portrait",
						"game_date": "",
						"game_type": 0,
						"grade": 9,
						"highrewardcoin": 0,
						"icon": "http://download.mgc-games.com/access/upload/20191206/5de9c57b2cd0f.png",
						"id": 1000268,
						"marker": "",
						"name": "一起搭车",
						"packageurl": "http://download.mgc-games.com/sdkgame/1000268/Take a ride together_pack.zip",
						"pic": "",
						"play_num": 113,
						"publicity": "感受城市里最真实的快车接单体验，在这里你可以体验快车司机接送乘客的职责还可以锻炼玩家的驾驶技术\n而你想要更高级的车辆，更多的收入？动动手指合成更高级的车辆就可以实现你的一夜暴富的梦想",
						"tags": ["休闲", "赛车"],
						"title": "",
						"version": "1.1.1"
					},
					{
						"amount": "",
						"backgroundcolor": "",
						"classify": 7,
						"classify_game_id": "0",
						"deviceOrientation": "portrait",
						"game_date": "12-19",
						"game_type": 0,
						"grade": 9,
						"highrewardcoin": 0,
						"icon": "http://download.mgc-games.com/access/upload/20191206/5de9c5662bf6e.png",
						"id": 1000269,
						"marker": "",
						"name": "迷宫旋转",
						"packageurl": "http://download.mgc-games.com/sdkgame/1000269/Twizzle_pack.zip",
						"pic": "",
						"play_num": 650,
						"publicity": "只需要转动屏幕，不止可以走出迷宫，还可以收获机遇与奖励，收获游戏多样皮肤\r\n“嘿，请你小心点，别碰坏我才换的新衣服！“",
						"tags": ["休闲", "益智"],
						"title": "",
						"version": "1.0.1"
					},
					{
						"amount": "",
						"backgroundcolor": "",
						"classify": 7,
						"classify_game_id": "0",
						"deviceOrientation": "portrait",
						"game_date": "",
						"game_type": 0,
						"grade": 9,
						"highrewardcoin": 0,
						"icon": "http://download.mgc-games.com/access/upload/20200318/5e7192144a8de.png",
						"id": 1001027,
						"marker": "",
						"name": "推推大乱斗",
						"packageurl": "http://download.mgc-games.com/sdkgame/1001027/ttdld_pack.zip",
						"pic": "",
						"play_num": 104,
						"publicity": "理发推推推，托尼老师上线啦～",
						"tags": ["休闲", "益智"],
						"title": "",
						"version": "1.0"
					}
				]
			}
		],
		gameList: []
	},
	{
		"bg_pic": "",
		"categoryList": [],
		"coins": 100,
		"coins_icon": "http://download.mgc-games.com/access/upload/44jinbi.png",
		"color_end": "",
		"color_start": "",
		"compact": 10,
		"gameList": [
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20191206/5de9c5988292c.png",
				"id": 1000267,
				"marker": "",
				"name": "鲲神变",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000267/Transformed fish_pack.zip",
				"pic": "http://download.mgc-games.com/access/upload/20191230/5e09ddfd4838d.png",
				"play_num": 393,
				"publicity": "穿越上古蛮荒，探索大千世界，挖掘灵石仙宝，搜集珍禽异兽。进入游戏捕获远古神兽，成为伟大的上古之神吧！\n开局一条鲲,进化全靠吞,上古异兽再现,山海异兽.强神兽进化,开局一条鲲,成长全靠吞,2019火爆游戏,邀您来将它进化,究竟能否吞噬成功?\n",
				"tags": ["休闲", "点击", "养成"],
				"title": "",
				"version": "1.0.7"
			}],
		"highrewardcoin": 0,
		"icon": "http://download.mgc-games.com/access/upload/20190923/5d879c086e0b2.png",
		"id": 75283717,
		"min_name": "",
		"name": "鲲神变",
		"rankList": [],
		"rewardcoefficient": 1,
		"showmore": 1,
		"showtitle": 1,
		"signList": [],
		"styleCode": "bigPic"
	},
	{
		id: "24",
		name: "新游上线",
		compact: "2",
		styleCode: "moreHorizontalList",
		showmore: "2",
		categoryList: [],
		rankList: [],
		gameList: [
			{
				id: "364306",
				name: "欢乐打豆豆",
				icon: "http://download.mgc-games.com/access/upload/20190319/5c909ce383dce.png",
				packageurl: "http://download.mgc-games.com/sdkgame/364306/happyhbeanbeans_pack.zip",
				version: "1.0.0",
				deviceOrientation: "portrait",
				play_num: "217",
				pic: "",
				publicity: "不让吃饭？OK！不让睡觉，也OK，不让打豆豆，那是不可能的！",
				tags: [],
				classify: "7",
				backgroundcolor: ""
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20200318/5e7191e7ba0b6.jpg",
				"id": 1001031,
				"marker": "",
				"name": "我不叫塔防",
				"packageurl": "http://download.mgc-games.com/sdkgame/1001031/wbjtf_pack.zip",
				"pic": "",
				"play_num": 117,
				"publicity": "快来看看，你能够闯几关？",
				"tags": ["休闲", "益智"],
				"title": "",
				"version": "1.0.2"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20200317/5e7040e9cd612.jpg",
				"id": 1001025,
				"marker": "",
				"name": "魔力套圈",
				"packageurl": "http://download.mgc-games.com/sdkgame/1001025/mltq_pack.zip",
				"pic": "",
				"play_num": 184,
				"publicity": "喵喵喵，小猫咪想家了，你可以帮忙吗？",
				"tags": ["休闲", "对战"],
				"title": "",
				"version": "1.0.1"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20200317/5e7044c13cbce.jpg",
				"id": 1000948,
				"marker": "",
				"name": "猜歌第一名",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000948/cgdym_pack.zip",
				"pic": "",
				"play_num": 540,
				"publicity": "猜歌第一名：看看你可以猜出几首～",
				"tags": ["休闲"],
				"title": "",
				"version": "1.0.1"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20200317/5e70444ea128e.png",
				"id": 1000970,
				"marker": "",
				"name": "霓虹弹珠",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000970/nhdz_pack.zip",
				"pic": "",
				"play_num": 232,
				"publicity": "霓虹弹珠是一款热门的消除类游戏，有多变的弹珠形象，快来看看吧～",
				"tags": ["休闲", "消除"],
				"title": "",
				"version": "1.0.1"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20200317/5e70442d0715d.jpeg",
				"id": 1000971,
				"marker": "",
				"name": "一杆入洞",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000971/ygrd_pack.zip",
				"pic": "",
				"play_num": 477,
				"publicity": "快来看看你能不能一杆入洞！",
				"tags": ["休闲", "策略"],
				"title": "",
				"version": "1.0.1"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20200317/5e70450f13612.png",
				"id": 1000946,
				"marker": "",
				"name": "魔力转圈",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000946/mlzq_pack.zip",
				"pic": "",
				"play_num": 105,
				"publicity": "一款魔性的小游戏，越玩越好玩～",
				"tags": ["休闲", "解谜"],
				"title": "",
				"version": "1.0"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20200317/5e7044eb9418e.jpg",
				"id": 1000947,
				"marker": "",
				"name": "罗丽厨娘",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000947/llcn_pack.zip",
				"pic": "",
				"play_num": 104,
				"publicity": "选择你的制服，开始制作料理吧！",
				"tags": ["休闲"],
				"title": "",
				"version": "1.0.2"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20200317/5e7045220fc74.png",
				"id": 1000945,
				"marker": "",
				"name": "麻将消除乐",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000945/mjxcl_pack.zip",
				"pic": "",
				"play_num": 112,
				"publicity": "麻将消除乐，一款国粹与现代结合的游戏～",
				"tags": ["休闲", "消除"],
				"title": "",
				"version": "1.0.1"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20200306/5e626b4e31673.png",
				"id": 1000873,
				"marker": "",
				"name": "集合大乱斗",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000873/zj_pack.zip",
				"pic": "",
				"play_num": 91,
				"publicity": "集合大乱斗集合大乱斗集合大乱斗集合大乱斗集合大乱斗",
				"tags": [],
				"title": "",
				"version": "1.0.1"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "landscape",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20200306/5e6267eb38cb8.png",
				"id": 1000880,
				"marker": "",
				"name": "弓箭手王者",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000880/The king of Archers_pack.zip",
				"pic": "",
				"play_num": 104,
				"publicity": "每个人从小都有个英雄梦，你现在是英雄吗？是不是都不要紧，因为在这里，你的英雄梦可以实现！\r\n\r\n仗剑天下，劫富济贫，惩恶扬善，行侠仗义，一切的一切只需要你选择恰当，手滑够快！\r\n\r\n【游戏特色】\r\n-中国风界面，卡通画风，老少咸宜！\r\n-简单操作，一箭一个，游戏轻松又解压！\r\n-上下瞄准，按住连射，残血也能秀起来！\r\n-随机技能，任你组合，敌人死法你说了算！\r\n-奇遇事件，惊喜不断，命运女神总会眷",
				"tags": [],
				"title": "",
				"version": "1.0.5"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20200227/5e5749ce90c1f.png",
				"id": 1000894,
				"marker": "",
				"name": "无限找茬",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000894/wxzc_pack.zip",
				"pic": "",
				"play_num": 213,
				"publicity": "无限找茬，看看你的眼力怎么样～",
				"tags": ["休闲"],
				"title": "",
				"version": "1.0.1"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20200203/5e3779e926c8b.png",
				"id": 1000587,
				"marker": "",
				"name": "功夫大侠",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000587/gfdx_pack.zip",
				"pic": "",
				"play_num": 107,
				"publicity": "功夫大侠，谁与争锋",
				"tags": ["休闲", "竞技", "策略"],
				"title": "",
				"version": "1.0.4"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20200116/5e1fbf9cc4a38.png",
				"id": 1000530,
				"marker": "",
				"name": "我要飞升",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000530/woyaofeisheng_pack.zip",
				"pic": "",
				"play_num": 107,
				"publicity": "我要飞升～一款超赞的游戏",
				"tags": ["休闲"],
				"title": "",
				"version": "1.0.5"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20200120/5e256c34652a0.png",
				"id": 1000584,
				"marker": "",
				"name": "成语群雄传",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000584/cyqxz_pack.zip",
				"pic": "",
				"play_num": 137,
				"publicity": "成语版的群雄斗争，等你来参与～",
				"tags": ["休闲"],
				"title": "",
				"version": "1.0.4"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "03-07",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20191226/5e043028e036b.png",
				"id": 1000370,
				"marker": "",
				"name": "挂机打僵尸",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000370/gjdjs_pack.zip",
				"pic": "",
				"play_num": 95,
				"publicity": "挂机打僵尸：\r\n僵尸类的射击游戏，有着超高的热血体验，带你领略不一般的射击效果\r\n是发泄压力的一个好的解压游戏",
				"tags": [],
				"title": "",
				"version": "1.0.1"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20200120/5e252a51af0b1.png",
				"id": 1000582,
				"marker": "",
				"name": "成语封神榜",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000582/cyfsb_pack.zip",
				"pic": "",
				"play_num": 320,
				"publicity": "成语封神榜，快来一起休闲吧！",
				"tags": ["休闲"],
				"title": "",
				"version": "1.0.3"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20191227/5e059c6a8ab97.png",
				"id": 1000371,
				"marker": "",
				"name": "激光球球",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000371/jgqq_pack.zip",
				"pic": "",
				"play_num": 203,
				"publicity": "激光球球：\n超炫的激光效果，通过手指滑动去躲避激光！\n保护好球球，是每一位勇士的责任！\n与球球同样颜色的激光是不会伤害球球的！",
				"tags": [],
				"title": "",
				"version": "1.0"
			}
		]
	},
	{
		id: "25",
		name: "客官饿了吗",
		compact: "10",
		styleCode: "bigPic",
		showmore: "2",
		categoryList: [],
		rankList: [],
		gameList: [
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20190930/5d91a61d55872.png",
				"id": 364720,
				"marker": "",
				"name": "客官饿了吗",
				"packageurl": "http://download.mgc-games.com/sdkgame/364720/Guest_pack.zip",
				"pic": "http://download.mgc-games.com/access/upload/20191221/5dfde646e3e21.jpg",
				"play_num": 275,
				"publicity": "这是一款集模拟经营+合成+收集类游戏\n通过给来自各地的客人提供上百种中国传统美食，收获解锁传奇菜谱中的每一道菜品，用心经营升级扩大酒楼规模。最终达成御赐满汉全席，名满全国的皇家传奇酒楼。",
				"tags": ["养成"],
				"title": "",
				"version": "1.4.8"
			}]
	},
	{
		id: "26",
		name: "休闲益智",
		compact: "5",
		styleCode: "horizontalList",
		showmore: "1",
		categoryList: [],
		rankList: [],
		gameList: [
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20200107/5e13f96b0b1c6.png",
				"id": 1000458,
				"marker": "",
				"name": "找茬高高手",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000458/A master of finding fault_pack.zip",
				"pic": "",
				"play_num": 506,
				"publicity": "找茬高高手：眼力大比拼，全民找不同，只有最强眼里达人才能找到这两张图的不同",
				"tags": [],
				"title": "",
				"version": "1.0.6"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20191227/5e059c4f75809.png",
				"id": 1000373,
				"marker": "",
				"name": "我要炸了",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000373/ I\u0027m going to fry_pack.zip",
				"pic": "",
				"play_num": 426,
				"publicity": "我要炸了：\n千万不要让小人掉下去，不然我就要炸了！千万人风靡的小游戏，赶紧来呼朋唤友来玩吧！！！",
				"tags": [],
				"title": "",
				"version": "1.0.1"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20200317/5e70441913af3.png",
				"id": 1000972,
				"marker": "",
				"name": "蛮荒异兽录",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000972/mhysl_pack.zip",
				"pic": "",
				"play_num": 458,
				"publicity": "这是一款玩起来就停不下来的游戏～",
				"tags": ["休闲", "单机"],
				"title": "",
				"version": "1.0.3"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20190830/5d68bc9234661.png",
				"id": 365003,
				"marker": "",
				"name": "速度漂移",
				"packageurl": "http://download.mgc-games.com/sdkgame/365003/sdupiaoyi_pack.zip",
				"pic": "",
				"play_num": 273,
				"publicity": "合成高级赛车，享受最快的速度，去征服最野的赛道",
				"tags": ["休闲"],
				"title": "",
				"version": "1.2.2"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "02-03",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20190829/5d676de898abe.png",
				"id": 364999,
				"marker": "",
				"name": "枪神训练营",
				"packageurl": "http://download.mgc-games.com/sdkgame/364999/qiangshenxunlianying_pack.zip",
				"pic": "",
				"play_num": 262,
				"publicity": "枪神训练营是一款模拟射击打靶游戏，玩家可通过合成获得更高级的武器。简单易懂好操作~",
				"tags": ["休闲", "对战", "射击"],
				"title": "",
				"version": "1.1.1"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "11-18",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20190626/5d12d604e05bd.png",
				"id": 364740,
				"marker": "",
				"name": "超人泡泡",
				"packageurl": "http://download.mgc-games.com/sdkgame/364740/bubblepop_pack.zip",
				"pic": "",
				"play_num": 254,
				"publicity": "一款非常值得玩的泡泡龙休闲游戏，挑战关卡，冲击高分！",
				"tags": ["休闲", "消除"],
				"title": "",
				"version": "1.1.1"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20190830/5d68ca123d332.png",
				"id": 365007,
				"marker": "",
				"name": "疯狂七巧板",
				"packageurl": "http://download.mgc-games.com/sdkgame/365007/fengkuangqiqiaoban_pack.zip",
				"pic": "",
				"play_num": 498,
				"publicity": "七巧板的冒险之旅，17152种形态等你来解锁！",
				"tags": ["休闲"],
				"title": "",
				"version": "1.2.2"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20190830/5d68c99e20af7.png",
				"id": 365006,
				"marker": "",
				"name": "全民七巧板",
				"packageurl": "http://download.mgc-games.com/sdkgame/365006/quanminqixiaob_pack.zip",
				"pic": "",
				"play_num": 375,
				"publicity": "超级魔性的休闲益智小游戏，每次都能玩上好几个小时！",
				"tags": ["休闲"],
				"title": "",
				"version": "1.1.1"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20190829/5d677718ab386.png",
				"id": 365001,
				"marker": "",
				"name": "拯救熊猫泡泡",
				"packageurl": "http://download.mgc-games.com/sdkgame/365001/zhengjiuxiongmaopaopao_pack.zip",
				"pic": "",
				"play_num": 265,
				"publicity": "这里有最好玩的泡泡龙消消乐，可爱的熊猫正呼唤你来！",
				"tags": ["休闲", "消除"],
				"title": "",
				"version": "1.1.1"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20190227/5c764fef25adb.png",
				"id": 364296,
				"marker": "",
				"name": "六角开心消",
				"packageurl": "http://download.mgc-games.com/sdkgame/364296/hexagonal_pack.zip",
				"pic": "",
				"play_num": 275,
				"publicity": "烧脑六边形消除，实在太过瘾了\n",
				"tags": ["休闲", "消除", "单机"],
				"title": "",
				"version": "1.0.1"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20200115/5e1e7975da6ca.png",
				"id": 1000514,
				"marker": "",
				"name": "花花也疯狂",
				"packageurl": "http://download.mgc-games.com/sdkgame/364296/hexagonal_pack.zip",
				"pic": "",
				"play_num": 275,
				"publicity": "烧脑六边形消除，实在太过瘾了\n",
				"tags": ["休闲", "消除", "单机"],
				"title": "",
				"version": "1.0.1"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20191021/5dad615dbd6f4.png",
				"id": 1000054,
				"marker": "",
				"name": "暖暖的衣柜",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000054/nuannuandeyigui_pack.zip",
				"pic": "",
				"play_num": 641,
				"publicity": "宫廷古装大秀审美较量开启",
				"tags": ["休闲", "养成", "女频"],
				"title": "",
				"version": "1.5.0"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "landscape",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20191206/5de9c766f0624.png",
				"id": 1000226,
				"marker": "",
				"name": "森林冰火人",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000226/Redboy and Bluegirl_pack.zip",
				"pic": "",
				"play_num": 87,
				"publicity": "森林冰火人一款策略冒险游戏，玩家需要通过操控冰与火两兄弟协调合作来过关逃出神庙，一款非常锻炼思考和策略的休闲益智游戏！\r\n最受孩子欢迎的冰火人来临！利用你的智慧帮助火焰男孩和冰霜女孩！\r\n冰火合作，收集专属钻石，找到森林神庙出口！一款游戏，给你双重体验！",
				"tags": [],
				"title": "",
				"version": "1.1.3"
			}
		]
	},
	{
		id: "27",
		name: "百战坦克",
		compact: "10",
		styleCode: "bigPic",
		showmore: "2",
		categoryList: [],
		rankList: [],
		gameList: [
			{
				"amount": "",
				"backgroundcolor": "#333089",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "landscape",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20191206/5de9c5ab302f8.png",
				"id": 1000266,
				"marker": "",
				"name": "百战坦克",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000266/pokey tanks_pack.zip",
				"pic": "http://download.mgc-games.com/access/upload/20200104/5e10200684e67.png",
				"play_num": 530,
				"publicity": "最真实的坦克1V1游戏，移动——瞄准——射击，快来与好友展开一场殊死搏斗吧！\n“我已经瞄准你了，请举手投降”，放弃无谓的抵抗",
				"tags": ["PK", "射击"],
				"title": "",
				"version": "1.1.6"
			}]
	},
	{
		id: "28",
		name: "今日推荐",
		compact: "2",
		styleCode: "moreHorizontalList",
		showmore: "2",
		categoryList: [],
		rankList: [],
		gameList: [
			{
				id: "364723",
				name: "合成塔防",
				icon: "http://download.mgc-games.com/access/upload/20190412/5cb03f7bc572f.png",
				packageurl: "http://download.mgc-games.com/sdkgame/364723/idleTower_pack.zip",
				version: "1.0.0",
				deviceOrientation: "portrait",
				play_num: "146",
				pic: "",
				publicity: "欢乐塔防，轻松合成，一起打怪兽~",
				tags: ["休闲", "在线玩", "烧脑"],
				classify: "7",
				backgroundcolor: ""
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "landscape",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20200110/5e17ec9dce9ca.png",
				"id": 1000454,
				"marker": "",
				"name": "球球大乱斗",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000454/HLQCQ_pack.zip",
				"pic": "",
				"play_num": 316,
				"publicity": "休闲与挑战并存的游戏，在这个球球的世界里，每个人都成为一颗独特的球球发展与生存是所有人的目标，刺激战场极限逃生。",
				"tags": ["休闲", "IO"],
				"title": "",
				"version": "1.1.2"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20200110/5e17ec8c9821b.png",
				"id": 1000455,
				"marker": "",
				"name": "全民切切切",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000455/QMQQQ_pack.zip",
				"pic": "",
				"play_num": 96,
				"publicity": "全民切切切是一款3D休闲小游戏，通过各式各样刀切除不一样水果蔬菜等道具，让你体验到切碎的快感。",
				"tags": ["休闲", "单机"],
				"title": "",
				"version": "1.0"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20200110/5e17ec207f251.png",
				"id": 1000906,
				"marker": "",
				"name": "合成农场",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000455/QMQQQ_pack.zip",
				"pic": "",
				"play_num": 96,
				"publicity": "全民切切切是一款3D休闲小游戏，通过各式各样刀切除不一样水果蔬菜等道具，让你体验到切碎的快感。",
				"tags": ["休闲", "单机"],
				"title": "",
				"version": "1.0"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "02-09",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20200114/5e1db42aeec7e.png",
				"id": 1000515,
				"marker": "",
				"name": "尸尸你别狂",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000515/Don\u0027t be crazy, zombie_pack.zip",
				"pic": "",
				"play_num": 146,
				"publicity": "《尸尸你别狂》是一款放置+合成+塔防的休闲小游戏，在游戏里玩家需要放置植物来抵御僵尸大军的进攻，通过不停地合成来壮大自己植物军团的力量，来打败越来越多的僵尸，收集更多的货币和宝物，不停地挑战自我。",
				"tags": ["休闲", "益智", "塔防"],
				"title": "",
				"version": "1.0.2"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "11-08",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20190919/5d8313c429dd1.jpg",
				"id": 1000008,
				"marker": "",
				"name": "养个神仙玩儿",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000008/YSX_pack.zip",
				"pic": "",
				"play_num": 665,
				"publicity": "这年头，神仙也创业啦！",
				"tags": ["传奇", "养成", "男频"],
				"title": "",
				"version": "1.3.1"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "landscape",
				"game_date": "10-28",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20191021/5dad6194baadc.png",
				"id": 1000043,
				"marker": "",
				"name": "闪电突击",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000043/Lightning Strike_pack.zip",
				"pic": "",
				"play_num": 450,
				"publicity": "火爆的吃鸡游戏，带上你的98K，做岛上最靓的仔，恭祝大吉大利，今晚吃鸡！",
				"tags": ["对战", "竞技", "射击"],
				"title": "",
				"version": "1.1.0"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20200114/5e1db4aa96e7d.png",
				"id": 1000500,
				"marker": "",
				"name": "女帝升职记",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000500/nvdishengzhi_pack.zip",
				"pic": "",
				"play_num": 265,
				"publicity": "民女出生偶然带莲花标记，从布衣素女，逆袭成女帝；唯美换装玩法，邂逅多类型蓝颜，给你不一样的女帝体验！",
				"tags": ["养成", "女频"],
				"title": "",
				"version": "1.0.1"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20191206/5de9c5e2da255.png",
				"id": 1000260,
				"marker": "",
				"name": "中餐厅",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000500/nvdishengzhi_pack.zip",
				"pic": "",
				"play_num": 265,
				"publicity": "民女出生偶然带莲花标记，从布衣素女，逆袭成女帝；唯美换装玩法，邂逅多类型蓝颜，给你不一样的女帝体验！",
				"tags": ["养成", "女频"],
				"title": "",
				"version": "1.0.1"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20190709/5d23f4db8227c.png",
				"id": 364859,
				"marker": "",
				"name": "军火工厂之枪神对决",
				"packageurl": "http://download.mgc-games.com/sdkgame/364859/Gunup_pack.zip",
				"pic": "",
				"play_num": 168,
				"publicity": "各种枪械任您挑选，看看谁才是枪神。",
				"tags": ["射击"],
				"title": "",
				"version": "1.2.0"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "02-08",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20200117/5e218db408d0c.png",
				"id": 1000528,
				"marker": "",
				"name": "刀剑领域",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000528/Dungeon \u0026 Fighter_pack.zip",
				"pic": "",
				"play_num": 411,
				"publicity": "地下城战记是一款动作+合成+挂机格斗的休闲小游戏，在游戏里玩家单独闯入地下城里冒险使用技能一路对抗地下城里的敌人。",
				"tags": ["传奇", "超爽", "策略"],
				"title": "",
				"version": "1.0.3"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "12-05",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20190929/5d908e2685186.png",
				"id": 364793,
				"marker": "",
				"name": "爆笑史小坑",
				"packageurl": "http://download.mgc-games.com/sdkgame/364793/baoxiao_pack.zip",
				"pic": "",
				"play_num": 249,
				"publicity": "\t外星人入侵？！好基友暴走？！女神被坏蛋拐跑了？！放心，这只是游戏主角「史小坑」千奇百怪的游戏故事！\n\t在《史小坑的爆笑生活1》中，玩家不但能揭开史小坑“整蛊专家”的愚人节搞怪套路、还能化身“科幻达人”，探索精彩星际对决的搞怪花招、甚至穿梭“坑爹神话世界”，演绎趣味十足的搞怪神话情节……\n\t众多离奇章节、稀奇古怪的脑洞关卡持续解锁加入中，现在就试试你逆向思考、找寻蛛丝马迹的解谜能力……到底能有",
				"tags": ["解谜", "史小坑", "坑爹游戏"],
				"title": "",
				"version": "2.4.2"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "landscape",
				"game_date": "11-05",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20191021/5dad60a26ecd5.png",
				"id": 1000070,
				"marker": "",
				"name": "乱斗荣耀",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000070/ Fighting glory_pack.zip",
				"pic": "",
				"play_num": 167,
				"publicity": "3V3、5V5、三方混战在线激情PK,简单、轻松上王者",
				"tags": ["对战", "PK", "竞技"],
				"title": "",
				"version": "1.1.0"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "landscape",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20191101/5dbc3100bea45.png",
				"id": 1000131,
				"marker": "",
				"name": "怪物工厂2",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000131/Monster Factory 2_pack.zip",
				"pic": "",
				"play_num": 295,
				"publicity": "怪物合成冲冲冲！",
				"tags": ["休闲", "塔防", "策略"],
				"title": "",
				"version": "1.2.0"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20191217/5df89a56cd6d2.png",
				"id": 1000343,
				"marker": "",
				"name": "开心消方块儿",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000343/KXXFKE_pack.zip",
				"pic": "",
				"play_num": 98,
				"publicity": "好玩的俄罗斯方块消除，经典消除小游戏",
				"tags": ["休闲", "消除"],
				"title": "",
				"version": "1.0"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "landscape",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20191113/5dcbbe358a99e.png",
				"id": 1000186,
				"marker": "",
				"name": "葫芦娃冲冲冲",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000186/huluwa_pack.zip",
				"pic": "",
				"play_num": 170,
				"publicity": "是“葫芦娃”官方授权的跑酷射击类游戏，带领着葫芦娃穿越过无数的山峦险境，向妖精们发起挑战，求出同伴",
				"tags": ["休闲", "跑酷"],
				"title": "",
				"version": "1.2.1"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "01-19",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20191226/5e043215ab864.png",
				"id": 1000281,
				"marker": "",
				"name": "首富的美梦",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000281/fonddream_pack.zip",
				"pic": "",
				"play_num": 102,
				"publicity": "春宵苦短，不如来做个梦吧，梦里啥都有！",
				"tags": ["坑爹游戏", "养成", "超爽"],
				"title": "",
				"version": "1.0.5"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20191226/5e043175b36f3.png",
				"id": 1000334,
				"marker": "",
				"name": "农场富家翁",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000334/nongchengfujiaweng_pack.zip",
				"pic": "",
				"play_num": 130,
				"publicity": "一款模拟经营小农场的游戏。游戏中农作物成熟会产生金币，可以通过手指随意滑动屏幕来收获金币，也可以设置自动收获农产品。通过种植并升级农作物来获得基础的金币，农作物等级越高，带来的收益就越大，土地越多，种的越多，收益越多。这样产生的金币就越多。这样循环播种收割，你也可以成为农场的大亨的。",
				"tags": [],
				"title": "",
				"version": "1.0.4"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20191206/5de9c77698248.png",
				"id": 1000207,
				"marker": "",
				"name": "方鸟向前冲",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000207/fangniaoxiangqianchong_pack.zip",
				"pic": "",
				"play_num": 513,
				"publicity": "《方鸟向前冲》一只方块造型的小鸟开启飞行闯关模式,动动手指来控制小鸟的飞行吧！",
				"tags": ["休闲", "虐心", "跑酷"],
				"title": "",
				"version": "1.0.1"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "01-12",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20191021/5dad61a654613.jpeg",
				"id": 1000037,
				"marker": "",
				"name": "极速冲冲冲",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000037/fallrace_pack.zip",
				"pic": "",
				"play_num": 95,
				"publicity": "滑动屏幕，控制角色左右移动，在美丽的云端上自由的奔跑",
				"tags": ["休闲"],
				"title": "",
				"version": "1.0.1"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "11-12",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20190726/5d3aae790ce63.png",
				"id": 364903,
				"marker": "",
				"name": "飞刀大逃杀",
				"packageurl": "http://download.mgc-games.com/sdkgame/364903/Knife.io_pack.zip",
				"pic": "",
				"play_num": 235,
				"publicity": "超级魔性刺激的飞刀游戏，超好玩，根本停不下来！",
				"tags": [],
				"title": "",
				"version": "1.1.1"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "landscape",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20191101/5dbc312e64e3f.png",
				"id": 1000128,
				"marker": "",
				"name": "火柴人你瞅啥",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000128/ Don\u0027t Look Matchman_pack.zip",
				"pic": "",
				"play_num": 293,
				"publicity": "你瞅啥？瞅你咋地！",
				"tags": ["单机", "超爽", "塔防"],
				"title": "",
				"version": "1.1.0"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20190830/5d68c014884b7.png",
				"id": 365004,
				"marker": "",
				"name": "快来划水",
				"packageurl": "http://download.mgc-games.com/sdkgame/365004/kuailaihuashui_pack.zip",
				"pic": "",
				"play_num": 243,
				"publicity": "可以滑翔飞行的水上滑梯竞速游戏！",
				"tags": ["休闲", "体育", "竞技"],
				"title": "",
				"version": "1.1.2"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "02-15",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20200114/5e1db4738bf69.png",
				"id": 1000503,
				"marker": "",
				"name": "韭菜先生大作战",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000503/Mr. leek\u0027s battle_pack.zip",
				"pic": "",
				"play_num": 376,
				"publicity": "魔性表情包，快乐又解压的休闲小游戏！",
				"tags": ["休闲", "养成", "超爽"],
				"title": "",
				"version": "1.0.4"
			}
		]
	},
	{
		id: "29",
		name: "成语中状元",
		compact: "10",
		styleCode: "bigPic",
		showmore: "2",
		categoryList: [],
		rankList: [],
		gameList: [
			{
				"amount": "2888元",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20190929/5d909a13e61e9.png",
				"id": 364735,
				"marker": "",
				"name": "成语中状元",
				"packageurl": "http://download.mgc-games.com/sdkgame/364952/cyzzy_pack.zip",
				"pic": "http://download.mgc-games.com/access/upload/20190903/5d6e5f11f1c51.png",
				"play_num": 172,
				"publicity": "《成语中状元》通过使用成语组合接龙的形式可以了解到更多的传统成语并且感受到游戏的乐趣。",
				"tags": [],
				"title": "闯关赚钱",
				"version": "1.0.5"
			}]
	},
	{
		id: "30",
		name: "轻松玩",
		compact: "5",
		styleCode: "horizontalList",
		showmore: "1",
		categoryList: [],
		rankList: [],
		gameList: [
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20190227/5c7658d24e377.png",
				"id": 364057,
				"marker": "",
				"name": "史上最坑爹的游戏1",
				"packageurl": "http://download.mgc-games.com/sdkgame/364057/keng1_pack.zip",
				"pic": "",
				"play_num": 679,
				"publicity": "奇思妙想、脑洞大开，清奇风靡的烧脑游戏\n",
				"tags": ["解谜", "史小坑", "坑爹游戏"],
				"title": "",
				"version": "2.8.0"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20191021/5dad612420096.png",
				"id": 1000060,
				"marker": "",
				"name": "烦恼史小坑",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000060/fannao1_pack.zip",
				"pic": "",
				"play_num": 367,
				"publicity": "史小坑的烦恼PK版上线啦！全新的实时在线答题！大量全新头脑风暴等你来挑战！快拉上小伙伴们一起来玩吧！",
				"tags": [],
				"title": "",
				"version": "1.1.0"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20191021/5dad6136925b2.png",
				"id": 1000059,
				"marker": "",
				"name": "水果切切切",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000059/Perfect Slices_pack.zip",
				"pic": "",
				"play_num": 489,
				"publicity": "水果切切切，菜刀往前冲！",
				"tags": ["休闲", "益智", "手速"],
				"title": "",
				"version": "1.0.2"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20190726/5d3ab3ef175f9.png",
				"id": 364905,
				"marker": "",
				"name": "欢乐刀剑",
				"packageurl": "http://download.mgc-games.com/sdkgame/364905/Sword king_pack.zip",
				"pic": "",
				"play_num": 201,
				"publicity": "一款创新玩法的io类游戏，通过对一大堆飞刀的熟练操控来进行混战，独创的龟缩防御机制让你能轻松秀翻对手。",
				"tags": ["休闲", "对战", "IO"],
				"title": "",
				"version": "1.3.2"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20190919/5d837b16278de.png",
				"id": 1000010,
				"marker": "",
				"name": "跳舞的球球",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000010/Dancing ball_pack.zip",
				"pic": "",
				"play_num": 218,
				"publicity": "跳舞的球球是许多球类游戏之一，将快节奏的游戏与钢琴，吉他等高品质的音乐节奏相结合。这款游戏将为喜欢简单游戏的音乐游戏爱好者提供全新的体验。\n\n准备赶上节拍！随着美丽的节奏和每一个音乐节拍跳跃，然后尽可能多地跳跃！\n\n这是真正的众多球类音乐中的一个，用伟大的音乐来挑战你的朋友。\n\n如何玩 跳舞的球球\n1. 聆听音乐节拍，并使用音乐反射将球向左或向右拖动，以将球从瓦片引导至瓦片。总之，让一个球跳！\n2",
				"tags": ["休闲", "超难", "益智"],
				"title": "",
				"version": "1.0.1"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20191206/5de9c6c84d8b8.png",
				"id": 1000246,
				"marker": "",
				"name": "天天滑板",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000246/TTHB_pack.zip",
				"pic": "",
				"play_num": 142,
				"publicity": "街头滑板",
				"tags": ["休闲"],
				"title": "",
				"version": "1.1.3"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "01-13",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20191210/5def6b39024f6.jpg",
				"id": 1000298,
				"marker": "",
				"name": "极速摩托车",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000298/Speed Motorbike_pack.zip",
				"pic": "",
				"play_num": 93,
				"publicity": "极速摩托小游戏一款竞速类的赛车游戏，等你来挑战！",
				"tags": ["休闲", "益智", "赛车"],
				"title": "",
				"version": "1.1.0"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20200114/5e1db450cabfe.png",
				"id": 1000505,
				"marker": "",
				"name": "王者坦克大作战",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000505/King tank battle_pack.zip",
				"pic": "",
				"play_num": 122,
				"publicity": "放置合成类，坦克射击休闲游戏！",
				"tags": ["男频", "超爽", "射击"],
				"title": "",
				"version": "1.1.2"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20191227/5e059c190b413.png",
				"id": 1000378,
				"marker": "",
				"name": "我要住豪宅",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000378/Luxurious House_pack.zip",
				"pic": "",
				"play_num": 114,
				"publicity": "我要住豪宅，合成小游戏",
				"tags": ["休闲", "单机"],
				"title": "",
				"version": "1.0.5"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20190930/5d919b3f038c6.png",
				"id": 1000025,
				"marker": "",
				"name": "跳一跳联盟",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000025/Jump Jump！_pack.zip",
				"pic": "",
				"play_num": 391,
				"publicity": "高端走位，螺旋上分",
				"tags": ["休闲", "单机", "益智"],
				"title": "",
				"version": "1.0.8"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "landscape",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20190717/5d2ea47bf03b4.png",
				"id": 364886,
				"marker": "",
				"name": "天天超车",
				"packageurl": "http://download.mgc-games.com/sdkgame/364886/RacingCar_pack.zip",
				"pic": "",
				"play_num": 126,
				"publicity": "模拟驾驶，赛车",
				"tags": [],
				"title": "",
				"version": "1.1.2"
			},
			{
				"amount": "",
				"backgroundcolor": "",
				"classify": 7,
				"classify_game_id": "0",
				"deviceOrientation": "portrait",
				"game_date": "",
				"game_type": 0,
				"grade": 9,
				"highrewardcoin": 0,
				"icon": "http://download.mgc-games.com/access/upload/20190924/5d89af911e972.png",
				"id": 1000013,
				"marker": "",
				"name": "植物打僵尸",
				"packageurl": "http://download.mgc-games.com/sdkgame/1000013/PlantAndZombie_pack.zip",
				"pic": "",
				"play_num": 655,
				"publicity": "不一样的僵尸，不同的体验，快来加入吧！",
				"tags": ["休闲", "养成"],
				"title": "",
				"version": "1.1.1"
			}
		]
	},
	{
		id: "31",
		name: "六边形消除",
		compact: "10",
		styleCode: "bigPic",
		showmore: "2",
		categoryList: [],
		rankList: [],
		gameList: [
			{
				id: "364286",
				name: "六边形消除",
				icon: "http://download.mgc-games.com/access/upload/20190304/5c7d2f4c173e9.png",
				packageurl: "http://download.mgc-games.com/sdkgame/364286/hexagonelimination_pack.zip",
				version: "1.0",
				deviceOrientation: "portrait",
				play_num: "245",
				pic: "http://download.mgc-games.com/access/gamecenter/pic/lbxxc.jpg",
				publicity: "全新玩法，纵横变换，烧脑有趣，创意满满！",
				tags: ["休闲", "消除", "六边形"],
				classify: "7",
				backgroundcolor: ""
			}
		]
	}
]

export const BANNER = {
	id: "19",
	name: "轮播图",
	compact: "1",
	styleCode: "rotationChart",
	showmore: "2",
	categoryList: [],
	rankList: [],
	gameList: [
		{
			id: "364720",
			name: "客官饿了吗",
			icon: "http://download.mgc-games.com/access/upload/20190410/5cad967fde972.png",
			packageurl: "http://download.mgc-games.com/sdkgame/364720/Guest_pack.zip",
			version: "1.2.0",
			deviceOrientation: "portrait",
			play_num: "241",
			pic: "http://download.mgc-games.com/access/gamecenter/banner/kgelm.jpeg",
			publicity: "这是一款集模拟经营+合成+收集类游戏\r\n通过给来自各地的客人提供上百种中国传统美食，收获解锁传奇菜谱中的每一道菜品，用心经营升级扩大酒楼规模。最终达成御赐满汉全席，名满全国的皇家传奇酒楼。",
			tags: ["休闲", "点击", "养成"],
			classify: "7",
			backgroundcolor: ""
		},
		{
			"amount": "",
			"backgroundcolor": "#082655",
			"classify": 7,
			"classify_game_id": "0",
			"deviceOrientation": "landscape",
			"game_date": "",
			"game_type": 0,
			"grade": 9,
			"highrewardcoin": 0,
			"icon": "http://download.mgc-games.com/access/upload/20190806/5d4954e108f71.jpg",
			"id": 364942,
			"marker": "",
			"name": "火柴人冲突",
			"packageurl": "http://download.mgc-games.com/sdkgame/364942/Matchman Conflict_pack.zip",
			"pic": "http://download.mgc-games.com/access/upload/20200104/5e101f8c68fa3.png",
			"play_num": 653,
			"publicity": "从前有根火柴挠了挠头，然后它就着了！",
			"tags": ["休闲", "在线玩", "策略"],
			"title": "",
			"version": "1.1.7"
		},
		{
			"amount": "",
			"backgroundcolor": "#882AA5",
			"classify": 7,
			"classify_game_id": "0",
			"deviceOrientation": "portrait",
			"game_date": "",
			"game_type": 0,
			"grade": 9,
			"highrewardcoin": 0,
			"icon": "http://download.mgc-games.com/access/upload/20191206/5de9c5d2461cb.png",
			"id": 1000262,
			"marker": "",
			"name": "全民找茬",
			"packageurl": "http://download.mgc-games.com/sdkgame/1000262/find diff_pack.zip",
			"pic": "http://download.mgc-games.com/access/upload/20200104/5e101f650baf2.png",
			"play_num": 202,
			"publicity": "经典找茬找不同小游戏",
			"tags": [],
			"title": "",
			"version": "1.1.0"
		}
	]
}
